apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |  
    - rolearn: arn:aws:iam::730335486616:role/EKSJenkins
      username: system:node:{{ip-172-31-20-189.eu-north-1.compute.internal}}
      groups:
        - system:bootstrappers
        - system:nodes
