apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |  
    - rolearn: arn:aws:iam::730335486616:role/eks-worker-nodes-NodeInstanceRole-BbHpTPBlbeiE
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
